import { StyleSheet } from "react-native";
import { colors } from "./colors";
export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  safe: { flex: 1, backgroundColor: colors.background },
  login: { flex: 1, justifyContent: "center", paddingHorizontal: 28 },
  logo: {
    width: 52,
    height: 52,
    borderRadius: 22,
    backgroundColor: colors.accent,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 18,
  },
  play: {
    marginLeft: 4,
    width: 0,
    height: 0,
    borderTopWidth: 9,
    borderBottomWidth: 9,
    borderLeftWidth: 15,
    borderTopColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "#FFFFFF",
  },
  brand: {
    color: colors.accent,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 2.4,
  },
  loginTitle: {
    color: colors.text,
    fontSize: 38,
    lineHeight: 44,
    fontWeight: "800",
    marginTop: 12,
    maxWidth: 330,
  },
  register: { paddingHorizontal: 28 },
  registerText: { color: colors.accent, fontWeight: "800" },
  copy: {
    color: colors.secondary,
    fontSize: 16,
    lineHeight: 24,
    marginTop: 12,
  },
  form: { marginTop: 28 },
  label: {
    color: colors.secondary,
    fontWeight: "700",
    fontSize: 13,
    marginBottom: 8,
    marginTop: 14,
  },
  input: {
    backgroundColor: colors.panel,
    color: colors.text,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 54,
    borderRadius: 18,
    paddingHorizontal: 16,
    fontSize: 16,
  },
  error: {
    color: "#FFB4BB",
    backgroundColor: "#301F25",
    padding: 16,
    borderRadius: 16,
    lineHeight: 21,
    marginTop: 14,
  },
  primary: {
    backgroundColor: colors.accent,
    minHeight: 54,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  primaryText: { color: "#FFFFFF", fontWeight: "800", fontSize: 16 },
  demo: { height: 48, justifyContent: "center", alignItems: "center" },
  demoText: { color: colors.secondary, fontWeight: "700" },
  privateText: {
    color: colors.muted,
    textAlign: "center",
    fontSize: 12,
    marginTop: 24,
  },
  catalog: { padding: 20, paddingBottom: 48 },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 8,
    marginBottom: 20,
  },
  eyebrow: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 1.6,
  },
  homeTitle: {
    color: colors.text,
    fontSize: 30,
    fontWeight: "800",
    marginTop: 5,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: colors.accent, fontWeight: "900", fontSize: 17 },
  adminBanner: {
    backgroundColor: "#10271f",
    borderColor: "#1e6649",
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
    marginBottom: 18,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  adminTitle: { color: colors.accent, fontWeight: "900", fontSize: 15 },
  adminArrow: { color: colors.accent, fontSize: 30 },
  search: {
    height: 50,
    borderRadius: 15,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    paddingHorizontal: 16,
    fontSize: 15,
    marginBottom: 20,
  },
  hero: {
    height: 270,
    borderRadius: 22,
    overflow: "hidden",
    justifyContent: "flex-end",
    backgroundColor: colors.panel,
  },
  heroContent: { padding: 20 },
  heroTitle: {
    color: colors.text,
    fontSize: 27,
    fontWeight: "800",
    marginTop: 6,
  },
  track: {
    height: 4,
    backgroundColor: "rgba(255,255,255,.25)",
    borderRadius: 4,
    marginTop: 16,
  },
  fill: {
    width: "42%",
    height: 4,
    backgroundColor: colors.accent,
    borderRadius: 4,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: 21,
    fontWeight: "800",
    marginTop: 28,
    marginBottom: 14,
  },
  row: { gap: 14 },
  card: { flex: 1, maxWidth: "48%", marginBottom: 22 },
  poster: {
    width: "100%",
    aspectRatio: 0.7,
    borderRadius: 22,
    backgroundColor: colors.panel,
  },
  cardTitle: {
    color: colors.text,
    fontWeight: "800",
    fontSize: 15,
    marginTop: 10,
  },
  cardMeta: { color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 5 },
  details: { paddingBottom: 50 },
  detailsHero: { height: 410, marginBottom: -30 },
  back: {
    margin: 18,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(5,10,16,.75)",
    alignItems: "center",
    justifyContent: "center",
  },
  backText: { color: colors.text, fontSize: 36, lineHeight: 39, marginTop: -3 },
  detailsTitle: {
    color: colors.text,
    fontSize: 31,
    fontWeight: "900",
    paddingHorizontal: 22,
  },
  detailsMeta: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: "700",
    paddingHorizontal: 22,
    marginTop: 8,
  },
  description: {
    color: colors.secondary,
    fontSize: 16,
    lineHeight: 25,
    paddingHorizontal: 22,
    marginTop: 20,
  },
  sideMargin: { marginHorizontal: 22 },
  info: {
    marginVertical: 10,
    padding: 20,
    borderRadius: 22,
    backgroundColor: colors.panel,
    borderWidth: 1,
    borderColor: colors.border,
  },
  infoTitle: { color: colors.text, fontSize: 15, fontWeight: "800" },
  infoText: {
    color: colors.secondary,
    fontSize: 13,
    lineHeight: 20,
    marginTop: 6,
  },
  profileAvatar: {
    alignSelf: "center",
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 35,
    marginBottom: 22,
  },
  profileLetter: { color: "#FFFFFF", fontSize: 35, fontWeight: "900" },
  center: { textAlign: "center" },
  logout: {
    marginHorizontal: 22,
    height: 52,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#7f1d1d",
    alignItems: "center",
    justifyContent: "center",
  },
  logoutText: { color: "#fda4af", fontWeight: "800" },
  adminHeader: { flexDirection: "row", alignItems: "center" },
  adminPageTitle: { color: colors.text, fontSize: 25, fontWeight: "900" },
  adminContent: { padding: 22 },
  adminStats: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: colors.panel,
    borderRadius: 18,
    padding: 20,
  },
  statNumber: {
    color: colors.text,
    fontSize: 26,
    fontWeight: "900",
    textAlign: "center",
  },
  adminMovie: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.panel,
    borderRadius: 22,
    padding: 10,
    marginBottom: 10,
  },
  adminPoster: { width: 52, height: 72, borderRadius: 9 },
  adminMovieInfo: { flex: 1, paddingHorizontal: 12 },
});
